### ISSUE TITLE
table registration: image size issue?

### ISSUE THREAD

**Issue by DRRV** [TUWien/ReadModules#13]
for a document, image sizes (esp width) may vary. it seems that the table registration does not cope with this (wrong registration, but I am not sure of the real reason, i am assuming this is due to the width variation.
![s_freyung_023-01_0001](https://cloud.githubusercontent.com/assets/12894622/26302213/cf1e7fdc-3ee3-11e7-8b98-0297dc714716.jpg)

![s_freyung_023-01_0025](https://cloud.githubusercontent.com/assets/12894622/26302254/eb35bd48-3ee3-11e7-8312-a936d54e1765.jpg)

**Comment by DRRV** [comment]
previous images from (ABP First collection; S_Freyung_023-01)

**Comment by flow79** [comment]
this should be solved with the new release; parameters for width variation can be set in the settings
