### ISSUE TITLE
PageXML image width, height

### ISSUE THREAD

**Issue by DRRV** [TUWien/ReadModules#6]
plugin LA: the  image width, height values in the Pagexml are reversed:
<Page imageFilename="CH-BAR#E1004.1#1000-9#134#2.pdf-0.jpg" **imageWidth**="4875" **imageHeight**="3258">

OK for lines deteection plugin:
    <Page imageFilename="CH-BAR#E1004.1#1000-9#134#2.pdf-0.jpg" imageWidth="3258" imageHeight="4875">

**Comment by diemmarkus** [comment]
thx!
